# Generated by Django 4.1.7 on 2023-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('profileIconId', models.IntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('summonerLevel', models.IntegerField()),
            ],
        ),
    ]
