# Generated by Django 4.1.7 on 2023-03-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='profileIconId',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='puuid',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='revisionDate',
        ),
    ]
